### ISSUE TITLE
Exception Handling for missing file/directory

### ISSUE THREAD

**Issue by ChrisHill8** [phi-grib/flame#126]
After reinstalling flame `flame -c manage -a list` yields a FileNotFoundError, when `flame -c config` was not executed beforehand. This exception should be caught and a meaningful error message prompted to the user.

Also the readme.md contains `flame -c conf` which no longer works in the current version and should be changed to `flame -c config`

Error code (deleted YAMLLoadWarning):
`(flame) christoph:flame$flame -c manage -a list`
`INFO - Models found in repository:
Traceback (most recent call last):
  File "/anaconda3/envs/flame/bin/flame", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/envs/flame/lib/python3.6/site-packages/flame/flame_scr.py", line 154, in main
    success, results = context.manage_cmd(args)
  File "/anaconda3/envs/flame/lib/python3.6/site-packages/flame/context.py", line 197, in manage_cmd
    success, results = manage.action_list(args.endpoint)
  File "/anaconda3/envs/flame/lib/python3.6/site-packages/flame/manage.py", line 203, in action_list
    for x in os.listdir(rdir):
FileNotFoundError: [Errno 2] No such file or directory: '/home/testmodels'`

**Comment by manuelpastor** [comment]
You are right, the README has a typo and should read "flame -c config". It is now corrected

The configuration status testing has been completely rewritten and is now more robust. It should issue informative messages in any error condition
