### ISSUE TITLE
path error whilst building

### ISSUE THREAD

**Issue by kpinto-gil** [phi-grib/flame#61]
(flame) [kpinto@ulises 6-model]$ flame -c build -e MyModel -f tr-DEG.sdf 
CRITICAL ERROR: unable to load parameter file.Running with fallback defaults
Traceback (most recent call last):
  File "/home/kpinto/miniconda3/envs/flame/bin/flame", line 11, in <module>
    load_entry_point('flame', 'console_scripts', 'flame')()
  File "/phi/users/kpinto/flame/flame/flame_scr.py", line 142, in main
    success, results = context.build_cmd(model)
  File "/phi/users/kpinto/flame/flame/context.py", line 142, in build_cmd
    shutil.copy(ifile, lfile)
  File "/home/kpinto/miniconda3/envs/flame/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/kpinto/miniconda3/envs/flame/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/phi/users/kpinto/flame/flame_models/MyModel/dev/tr-DEG.sdf'

**Comment by BielStela** [comment]
Issue is in parameter.yml `normalize_method:`. The value is written as a list ( with new line and `-`). Since null is evaluated to `None` the yml parser return `[None]` wich python evaluates to True since it is not an empty list. This causes the `if not method `  in idata.py to return false when null is set in paramenters.yml. 

Fix: Write normalize_method as a value ---> `normalize_method: null`
