### ISSUE TITLE
Building Qualitative models

### ISSUE THREAD

**Issue by kpinto-gil** [phi-grib/flame#66]
flame) [kpinto@ulises 0-rdkit-properties]$ flame -c build -e INF-ql-RF -f ../../../1-test/pr-InF-3D-moka.sdf
>>> recycling data >>> /phi/users/kpinto/flame/flame_models/INF-ql-RF/dev/data.pkl
running sumbsmapling
tune_parameters
metric: f1
best parameters:  {'class_weight': None, 'max_features': 'sqrt', 'n_estimators': 25, 'oob_score': True, 'random_state': 46}
found in:  2.9187703132629395  seconds
Traceback (most recent call last):
  File "/home/kpinto/miniconda3/envs/flame/bin/flame", line 11, in <module>
    load_entry_point('flame', 'console_scripts', 'flame')()
  File "/phi/users/kpinto/flame/flame/flame_scr.py", line 142, in main
    success, results = context.build_cmd(model)
  File "/phi/users/kpinto/flame/flame/context.py", line 145, in build_cmd
    success, results = build.run(lfile)
  File "/phi/users/kpinto/flame/flame/build.py", line 83, in run
    results = learn.run()
  File "/phi/users/kpinto/flame/flame/learn.py", line 123, in run
    self.run_internal()
  File "/phi/users/kpinto/flame/flame/learn.py", line 96, in run_internal
    success, results = model.validate()
  File "/phi/users/kpinto/flame/flame/stats/base_model.py", line 391, in validate
    success, results = self.CF_qualitative_validation()
  File "/phi/users/kpinto/flame/flame/stats/base_model.py", line 248, in CF_qualitative_validation
    self.sensitivity = (self.TP / (self.TP + self.FN))
ZeroDivisionError: division by zero

**Comment by josecarlosgomezt** [comment]
Exception handling updated to catch this.
